### ISSUE TITLE
uboot build error with conflict define of crc32

### ISSUE THREAD

**Issue by tonghuix** [jserv/stm32f429-linux-builder#5]
```
In file included from crc32.c:20:0:
/home/tonghuix/git-pro/stm32f429-linux-builder/u-boot/include/u-boot/zlib.h:667:23: error: conflicting types for 'crc32'
 ZEXTERN  uInt ZEXPORT crc32  OF((uInt crc, const Bytef *buf, uInt len));
                       ^~~~~
In file included from /home/tonghuix/git-pro/stm32f429-linux-builder/u-boot/include/common.h:692:0,
                 from crc32.c:12:
/home/tonghuix/git-pro/stm32f429-linux-builder/u-boot/include/u-boot/crc.h:29:10: note: previous declaration of 'crc32' was here
 uint32_t crc32 (uint32_t, const unsigned char *, uint);
          ^~~~~
```

Build using:

Ubuntu 17.10 Artful
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors 6-2017-q4-major) 6.3.1 20170620 (release) [ARM/embedded-6-branch revision 249437]

**Comment by tonghuix** [comment]
It seems the newer version U-boot support STM32F429-discovery directly.

I tested it building successfully, and I don't test it on the board.

ref: http://blog.csdn.net/tcjy1000/article/details/51475438

**Comment by jserv** [comment]
Please read `READMD.md` carefully. Only GNU toolchain arm-2010q1 built by CodeSourcery is known to work;
