### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by alicanuzun** [jserv/stm32f429-linux-builder#6]
I am trying to install uclinux on my stm32f429I discovery board. I get error:

`  CC      kernel/fork.o   CC      kernel/exec_domain.o   CC      kernel/panic.o   CC      kernel/printk.o   CC      kernel/cpu.o   CC      kernel/exit.o   CC      kernel/itimer.o   TIMEC   kernel/timeconst.h Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /home/acd/stm32f429-linux-builder/uclinux/kernel/timeconst.pl line 373. /home/acd/stm32f429-linux-builder/uclinux/kernel/Makefile:133: recipe for target 'kernel/timeconst.h' failed make[6]: *** [kernel/timeconst.h] Error 255 /home/acd/stm32f429-linux-builder/uclinux/Makefile:884: recipe for target 'kernel' failed make[5]: *** [kernel] Error 2 Makefile:126: recipe for target 'sub-make' failed make[4]: *** [sub-make] Error 2 /home/acd/stm32f429-linux-builder/uclinux/Makefile:441: recipe for target 'xipImage' failed make[3]: *** [xipImage] Error 2 Makefile:126: recipe for target 'sub-make' failed make[2]: *** [sub-make] Error 2 make[2]: Leaving directory '/home/acd/stm32f429-linux-builder/uclinux' mk/kernel.mak:2: recipe for target 'build-kernel' failed make[1]: *** [build-kernel] Error 2 make[1]: Leaving directory '/home/acd/stm32f429-linux-builder' Makefile:39: recipe for target 'stamp-kernel' failed make: *** [stamp-kernel] Error 2`

**Comment by raspiduino** [comment]
Same
Until now!

**Comment by jserv** [comment]
> Same
> Until now!

Unfortunately, I tend to discontinue this project because Linux kernel upstream already merged Arm Cortex-M specific changes.

**Comment by raspiduino** [comment]
@jserv I found a fix for that problem:
From [this](https://stackoverflow.com/questions/41980796/cant-use-definedarray-warning-in-converting-obj-to-h), you just need to change the file `stm32f429-linux-builder/uclinux/kernel/timeconst.pl` line 373 from `if (!defined(@val))` to `if (!@val)` and then everything will be fine!

Should I fork and open a pull request for this?

**Comment by jserv** [comment]
> @jserv I found a fix for that problem:
> From [this](https://stackoverflow.com/questions/41980796/cant-use-definedarray-warning-in-converting-obj-to-h), you just need to change the file `stm32f429-linux-builder/uclinux/kernel/timeconst.pl` line 373 from `if (!defined(@val))` to `if (!@val)` and then everything will be fine!

I appreciate your interest in this project. Please send pull request.

**Comment by raspiduino** [comment]
This bug is in a file in https://github.com/raspiduino/uclinux, so I think I will send pull request to that repo.
Also, this is fixed, so could you close this issue?

**Comment by jserv** [comment]
> This bug is in a file in https://github.com/raspiduino/uclinux, so I think I will send pull request to that repo.
> Also, this is fixed, so could you close this issue? Thanks!

I would not change the uClinux repository. It would be better if we apply the necessary patches instead. You can create a new directory `patches` and run `patch -p1 < patches/001-necessary-fix.patch` in file `mk/download.mak`.
